module.exports = [
    [ {
        name: "body",
        background: " -moz-linear-gradient(center top , #F4FAFE 0%, #CCF0F0 100%) repeat fixed 0 0 transparent",
        fontfamily: "Gill Sans,Gill Sans MT,Calibri,sans-serif",
        fontsize: " 1.25em",
    },
     { name: "> .slide ",
        textshadow: " 1px 1px 1px rgba(255, 255, 255, 0.5)",
    },
     { name: "h1, h2, h3, h4, h5, h6 ",
        fontfamily: "Hoefler Text,Constantia,Palatino,Palatino Linotype,Book Antiqua,Georgia,serif",
    },
     { name: "h1 ",
        color: " #08455F",
    },
     { name: "h2 ",
        borderbottom: " 0 none",
        color: " #0B7495",
    },
     { name: ".cssreflections h2 ",
        lineheight: " 1",
    },
     { name: "h3 ",
        color: " #000000",
    },
     { name: "pre ",
        background: " none repeat scroll 0 0 #FFFFFF",
        bordercolor: " #CCDDEE",
        position: " relative",
    },
     { name: ".borderradius pre ",
        borderradius: " 5px 5px 5px 5px",
    },
     { name: ".csstransforms.boxshadow pre:before, .csstransforms.boxshadow .deckcontainer pre:after ",
        bottom: " 15px",
        boxshadow: " 0 15px 10px rgba(0, 0, 0, 0.7)",
        height: " 20%",
        maxwidth: " 300px",
        position: " absolute",
        width: " 50%",
        zindex: " -1",
    },
     { name: ".csstransforms.boxshadow .deckcontainer pre:before ",
        left: " 10px",
    },
     { name: ".csstransforms.boxshadow .deckcontainer pre:after ",
        right: " 10px",
    },
     { name: "code ",
        color: " #778899",
    },
     { name: "blockquote ",
        background: " none repeat scroll 0 0 #FFFFFF",
        border: " 1px solid #CCDDEE",
        color: " #000000",
        fontfamily: "Hoefler Text,Constantia,Palatino,Palatino Linotype,Book Antiqua,Georgia,serif",
        fontsize: " 2em",
        padding: " 1em 2em 0.5em",
        position: " relative",
    },
     { name: ".borderradius blockquote ",
        borderradius: " 5px 5px 5px 5px",
    },
     { name: ".boxshadow .deckcontainer blockquote:after ",
        borderradius: " 10px 10px 10px 10px / 100px 100px 100px 100px",
        bottom: " 10px",
        boxshadow: " 0 0 15px rgba(0, 0, 0, 0.6)",
        left: " 0",
        position: " absolute",
        right: " 50%",
        top: " 10px",
        zindex: " -1",
    },
     { name: "blockquote p ",
        margin: " 0",
    },
     { name: "blockquote cite ",
        color: " #888888",
        fontsize: " 0.5em",
        fontstyle: " normal",
        fontweight: " bold",
    },
     { name: ".deckcontainer blockquote:before ",
        color: " #CCF0F0",
        fontsize: " 5em",
        left: " 0",
        lineheight: " 1",
        position: " absolute",
        top: " 0",
        zindex: " 1",
    },
     { name: ".borderradius img ",
        borderradius: " 5px 5px 5px 5px",
    },
     { name: "a, a:hover, a:focus, a:active, .deckcontainer a:visited ",
        color: " #559999",
        textdecoration: " none",
    },
     { name: "a:hover, .deckcontainer a:focus ",
        textdecoration: " underline",
    },
     { name: ".deck-prev-link, .deck-next-link ",
        background: " none repeat scroll 0 0 #FFFFFF",
        opacity: " 0.5",
    },
     { name: ".deck-prev-link, .deck-prev-link:hover, .deck-prev-link:focus, .deck-prev-link:active, .deck-prev-link:visited, .deck-next-link, .deck-next-link:hover, .deck-next-link:focus, .deck-next-link:active, .deck-nextlink:visited ",
        color: " #559999",
    },
     { name: ".deck-prev-link:hover, .deck-prev-link:focus, .deck-next-link:hover, .deck-nextlink:focus ",
        opacity: " 1",
        textdecoration: " none",
    },
     { name: ".deck-status ",
        fontsize: " 0.6666em",
    },
     { name: ".deck-container.deck-menu .slide ",
        background: " none repeat scroll 0 0 transparent",
        borderradius: " 5px 5px 5px 5px",
    },
     { name: ".rgba .deck-container.deck-menu .slide ",
        background: " none repeat scroll 0 0 rgba(0, 0, 0, 0.1)",
    },
     { name: ".deck-container.deck-menu .slide.deck-current, .rgba .deck-container.deck-menu .slide.deck-current ",
        background: " none repeat scroll 0 0 #FFFFFF",
    },
     { name: ".goto-form ",
        background: " none repeat scroll 0 0 #FFFFFF",
        border: " 1px solid #CCDDEE",
        borderradius: " 5px 5px 5px 5px",
    },
     { name: "",
        background: " -moz-linear-gradient(center top , #F4FAFE 0%, #CCF0F0 100%) repeat fixed 0 0 transparent",
        fontfamily: "Gill Sans,Gill Sans MT,Calibri,sans-serif",
        fontsize: " 1.25em",
    },
    {
    name: "> .slide ",
        textshadow: " 1px 1px 1px rgba(255, 255, 255, 0.5)",
    },
    {
    name: "h1, h2, h3, h4, h5, h6 ",
        fontfamily: "Hoefler Text,Constantia,Palatino,Palatino Linotype,Book Antiqua,Georgia,serif",
    },
    {
    name: "h1 ",
        color: " #08455F",
    },
{
    name: "h2 ",
        borderbottom: " 0 none",
        color: " #0B7495",
    },
{
    name: ".cssreflections h2 ",
        lineheight: 1
    },
{
    name: "h3 ",
        color: " #000000",
    },
{
    name: "pre ",
        background: " none repeat scroll 0 0 #FFFFFF",
        bordercolor: " #CCDDEE",
        position: " relative",
    },
{
    name: ".borderradius pre ",
        borderradius: " 5px 5px 5px 5px",
    },
{
    name: ".csstransforms.boxshadow pre:before, .csstransforms.boxshadow .deckcontainer pre:after ",
        bottom: " 15px",
        boxshadow: " 0 15px 10px rgba(0, 0, 0, 0.7)",
        height: " 20%",
        maxwidth: " 300px",
        position: " absolute",
        width: " 50%",
        zindex: " -1",
    },
{
    name: ".csstransforms.boxshadow .deckcontainer pre:before ",
        left: " 10px",
    },
{
    name: ".csstransforms.boxshadow .deckcontainer pre:after ",
        right: " 10px",
    },
{
    name: "code ",
        color: " #778899",
    },
{
    name: "blockquote ",
        background: " none repeat scroll 0 0 #FFFFFF",
        border: " 1px solid #CCDDEE",
        color: " #000000",
        fontfamily: "Hoefler Text,Constantia,Palatino,Palatino Linotype,Book Antiqua,Georgia,serif",
        fontsize: " 2em",
        padding: " 1em 2em 0.5em",
        position: " relative",
    },
{
    name: ".borderradius blockquote ",
        borderradius: " 5px 5px 5px 5px",
    },
{
    name: ".boxshadow .deckcontainer blockquote:after ",
        borderradius: " 10px 10px 10px 10px / 100px 100px 100px 100px",
        bottom: " 10px",
        boxshadow: " 0 0 15px rgba(0, 0, 0, 0.6)",
        left: " 0",
        position: " absolute",
        right: " 50%",
        top: " 10px",
        zindex: " -1",
    },
{
    name: "blockquote p ",
        margin: " 0",
    },
{
    name: "blockquote cite ",
        color: " #888888",
        fontsize: " 0.5em",
        fontstyle: " normal",
        fontweight: " bold",
    },
{
    name: ".deckcontainer blockquote:before ",
        color: " #CCF0F0",
        fontsize: " 5em",
        left: " 0",
        lineheight: " 1",
        position: " absolute",
        top: " 0",
        zindex: " 1",
    },
{
    name: ".borderradius img ",
        borderradius: " 5px 5px 5px 5px",
    },
{
    name: ".deckcontainer *::-moz-selection ",
        background: " none repeat scroll 0 0 #08455F",
        color: " #FFFFFF",
    },
     { name: "blockquote p ",
        margin: " 0",
    },
     { name: "blockquote cite ",
        color: " #888888",
        fontsize: " 0.5em",
        fontstyle: " normal",
        fontweight: " bold",
    },
     { name: ".deckcontainer blockquote:before ",
        color: " #CCF0F0",
        fontsize: " 5em",
        left: " 0",
        lineheight: " 1",
        position: " absolute",
        top: " 0",
        zindex: " 1",
    },
     { name: ".borderradius img ",
        borderradius: " 5px 5px 5px 5px",
    },
     { name: ".deckcontainer *::-moz-selection ",
        background: " none repeat scroll 0 0 #08455F",
        color: " #FFFFFF",
    },
     { name: "a, a:hover, a:focus, a:active, .deckcontainer a:visited ",
        color: " #559999",
        textdecoration: " none",
    },
     { name: "a:hover, .deckcontainer a:focus ",
        textdecoration: " underline",
    },
     { name: ".deck-prev-link, .deck-next-link ",
        background: " none repeat scroll 0 0 #FFFFFF",
        opacity: " 0.5",
    },
     { name: ".deck-prev-link, .deck-prev-link:hover, .deck-prev-link:focus, .deck-prev-link:active, .deck-prev-link:visited, .deck-next-link, .deck-next-link:hover, .deck-next-link:focus, .deck-next-link:active, .deck-nextlink:visited ",
        color: "#559999"
    },
     { name: ".deck-prev-link:hover, .deck-prev-link:focus, .deck-next-link:hover, .deck-nextlink:focus ",
        opacity: " 1",
        textdecoration: " none",
        color: " #559999",
        textdecoration: " none",
    },
{
    name: "a:hover, .deckcontainer a:focus ",
        textdecoration: " underline",
    },
{
    name: ".deck-prev-link, .deck-next-link ",
        background: " none repeat scroll 0 0 #FFFFFF",
        opacity: " 0.5",
    },
{
    name: ".deck-prev-link, .deck-prev-link:hover, .deck-prev-link:focus, .deck-prev-link:active, .deck-prev-link:visited, .deck-next-link, .deck-next-link:hover, .deck-next-link:focus, .deck-next-link:active, .deck-nextlink:visited ",
        color: "#559999"
    },
{
    name: ".deck-prev-link:hover, .deck-prev-link:focus, .deck-next-link:hover, .deck-nextlink:focus ",
        opacity: " 1",
        textdecoration: " none",
    },
{
    name: ".deck-status ",
        fontsize: " 0.6666em",
    },
{
    name: ".deck-container.deck-menu .slide ",
        background: " none repeat scroll 0 0 transparent",
        borderradius: " 5px 5px 5px 5px",
    },
{
    name: ".rgba .deck-container.deck-menu .slide ",
        background: " none repeat scroll 0 0 rgba(0, 0, 0, 0.1)",
    },
{
    name: ".deck-container.deck-menu .slide.deck-current, .rgba .deck-container.deck-menu .slide.deck-current ",
        background: " none repeat scroll 0 0 #FFFFFF",
    },
{
   name: ".goto-form ",
        background: " none repeat scroll 0 0 #FFFFFF",
        border: " 1px solid #CCDDEE",
        borderradius: " 5px 5px 5px 5px",
    },
{ name: ".boxshadow .goto-form ",
        boxshadow: " 0 15px 10px -10px rgba(0, 0, 0, 0.5), 0 1px 4px rgba(0, 0, 0, 0.3), 0 0 40px rgba(0, 0, 0, 0.1) inset", }
    ],
    [
        { name:" h2",
                color: "green",
                fontsize: "1.9em"
            }
    ]
];
